<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BricksConfigTest\Bootstrap'  => __DIR__ . '/Bootstrap.php',
    'BricksConfigTest\ConfigTest' => __DIR__ . '/BricksConfigTest/ConfigTest.php',
);
