<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Bricks\Config\ClassLoader\Factories\ConfigAwareFactory' => __DIR__ . '/src/Bricks/Config/ClassLoader/Factories/ConfigAwareFactory.php',
    'Bricks\Config\Config'                                   => __DIR__ . '/src/Bricks/Config/Config.php',
    'Bricks\Config\ConfigAwareInterface'                     => __DIR__ . '/src/Bricks/Config/ConfigAwareInterface.php',
    'Bricks\Config\ConfigInterface'                          => __DIR__ . '/src/Bricks/Config/ConfigInterface.php',
    'Bricks\Config\Mapper\ConfigMapper'                      => __DIR__ . '/src/Bricks/Config/Mapper/Config.php',
    'Bricks\Config\Model\Config'                             => __DIR__ . '/src/Bricks/Config/Model/Config.php',
    'Bricks\Config\ServiceManager\ConfigFactory'             => __DIR__ . '/src/Bricks/Config/ServiceManager/ConfigFactory.php',
);
