<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Bricks\Config\ClassLoader\Factories\ConfigAwareFactory'        => __DIR__ . '/src/Bricks/Config/ClassLoader/Factories/ConfigAwareFactory.php',
    'Bricks\Config\ClassLoader\Factories\ConfigServiceAwareFactory' => __DIR__ . '/src/Bricks/Config/ClassLoader/Factories/ConfigServiceAwareFactory.php',
    'Bricks\Config\Config\ConfigAwareInterface'                     => __DIR__ . '/src/Bricks/Config/Config/ConfigAwareInterface.php',
    'Bricks\Config\Config\ConfigInterface'                          => __DIR__ . '/src/Bricks/Config/Config/ConfigInterface.php',
    'Bricks\Config\Config\DefaultConfig'                            => __DIR__ . '/src/Bricks/Config/Config/DefaultConfig.php',
    'Bricks\Config\ConfigService'                                   => __DIR__ . '/src/Bricks/Config/ConfigService.php',
    'Bricks\Config\ConfigServiceAwareInterface'                     => __DIR__ . '/src/Bricks/Config/ConfigServiceAwareInterface.php',
    'Bricks\Config\ConfigServiceInterface'                          => __DIR__ . '/src/Bricks/Config/ConfigServiceInterface.php',
    'Bricks\Config\Mapper\ConfigMapper'                             => __DIR__ . '/src/Bricks/Config/Mapper/Config.php',
    'Bricks\Config\Model\Config'                                    => __DIR__ . '/src/Bricks/Config/Model/Config.php',
    'Bricks\Config\ServiceManager\ConfigServiceFactory'             => __DIR__ . '/src/Bricks/Config/ServiceManager/ConfigServiceFactory.php',
);
