<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'BricksConfig\Module'                        => __DIR__ . '/Module.php',
    'Bricks\Config\Config'                       => __DIR__ . '/src/Bricks/Config/Config.php',
    'Bricks\Config\ConfigInterface'              => __DIR__ . '/src/Bricks/Config/ConfigInterface.php',
    'Bricks\Config\DefaultConfig'                => __DIR__ . '/src/Bricks/Config/DefaultConfig.php',
    'Bricks\Config\ServiceManager\ConfigFactory' => __DIR__ . '/src/Bricks/Config/ServiceManager/ConfigFactory.php',
    'Bricks\Config\Zend\Config'                  => __DIR__ . '/src/Bricks/Config/Zend/Config.php',
    'BricksConfigTest\Bootstrap'                 => __DIR__ . '/test/Bootstrap.php',
    'BricksConfigTest\ConfigTest'                => __DIR__ . '/test/BricksConfigTest/ConfigTest.php',
);
